### ISSUE TITLE
LogBatchPurger fails with error message Cannot have more than 10 chunks in a single operation. Please rearrange the data to reduce chunking.

### ISSUE THREAD

**Issue by EoghanMcMullen** [jongpie/NebulaLogger#146]
The error :"Cannot have more than 10 chunks in a single operation. Please rearrange the data to reduce chunking." is due to the arrangement of the recordsToDelete list in LogBatchPurger on line 50. 

Records are being added like so: 

> `for (Log__c log : scope) {
        recordsToDelete.addAll(log.LogEntries__r);
        recordsToDelete.add(log);
}`

This means you can end up with a list like this: 
>Log__c, LogEntry__c, LogEntry__c, Log__c, LogEntry__c, Log__c, LogEntry__c, Log__c, LogEntry__c, Log__c, LogEntry__c.

Apex will only chunk up to 10 times, this means your generic Sobject list needs to be sorted by Sobject type(to allow a generic deletion) like so:
>Log__c, Log__c, Log__c, Log__c, LogEntry__c, LogEntry__c, LogEntry__c, LogEntry__c.......

The above will chunk 2 times, one for the Log__c, one for the LogEntry__c.

A simple fix(but probably inefficient in a batch) is to call recordsToDelete.sort();

Probably a nicer way to do it is to have each SObject in it's own deletion list and the add them together once you've collected all the data. See below for example:
> `List<Log__c> logs = [SELECT Id, (SELECT Id FROM LogEntries__r) FROM Log__c LIMIT 500];

>List<Log__c> logsToDelete = new List<Log__c>();
>List<LogEntry__c> logsEntriesToDelete = new List<LogEntry__c>();

>for (Log__c log : logs) {
>    logsToDelete.add(log);
>    logsEntriesToDelete.addAll(log.LogEntries__r);
>}

>List<SObject> allRecords = new List<SObject>();
>allRecords.addAll(logsEntriesToDelete);
>allRecords.addAll(logsToDelete);
>delete allRecords;`

I did try implementing this but it wasn't playing nice with your test classes. If I get time I will look again. 

Thanks for all the work on this amazing Logger!

**Comment by jamessimone** [comment]
@EoghanMcMullen I know why that change wasn't working with the test classes and I've fixed it. I'll raise a PR for @jongpie to review prior to getting `v4.4.0`. Thanks for submitting this issue!

**Comment by jongpie** [comment]
@EoghanMcMullen I'ved merged @jamessimone's fix for this to the `main` branch (it's also included in managed package's [release v4.4.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.4.0))

**Comment by EoghanMcMullen** [comment]
@jamessimone @jongpie Thanks for getting this fixed so fast. Great work on this logger, it's amazing :)

**Comment by jamessimone** [comment]
@EoghanMcMullen no problem! Happy to help!

**Comment by EoghanMcMullen** [comment]
@jamessimone Got around to testing this fix but it was weirdly still throwing the chunking error. I ended up modifying the code to the following and all is good now. Unfortunate that it's 2 DMLs but not too bad performance wise. 

`List<Log__c> logsToDelete = new List<Log__c>();
            List<LogEntry__c> logEntriesToDelete = new List<LogEntry__c>();
            for (Log__c log : scope) {
                logEntriesToDelete.addAll(log.LogEntries__r);
                logsToDelete.add(log);
            }

            delete logEntriesToDelete;
            delete logsToDelete;
            Database.emptyRecycleBin(logEntriesToDelete);
            Database.emptyRecycleBin(logsToDelete);`

**Comment by jongpie** [comment]
@EoghanMcMullen I chatted with @jamessimone about this and went ahead and created PR #156 - it fixes this issue, plus another issue I noticed that could happen if 1 log has 200+ log entries.

I've merged the PR to the `main` branch, but there is also now an unlocked package (if you're interested in using that instead) - the latest unlocked package version [release v4.4.5](https://github.com/jongpie/NebulaLogger/releases/tag/v4.4.4) includes the 2 bugfixes
