### ISSUE TITLE
View Release Notes Button on Homepage

### ISSUE THREAD

**Issue by Senay-Ersen** [jongpie/NebulaLogger#529]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.10.6

### New Bug Summary

Hi @jongpie,

After deploying Nebula Logger Unlocked package to a higher environment, we see the **View Release Notes** button as in the below image and when we click it, we get 404 error. Also, when we click the **View Environment Details** button, the popup page comes up empty. What might I be missing to deploy/configure? 

Note: The user has **Logger: Admin** permission set. 

Thank you very much.

![ViewEnvDetailsBtn](https://github.com/jongpie/NebulaLogger/assets/126723243/9c51c7b5-0fb9-4f6d-a1c1-ebd0ad080caf)
![viewReleaseNotesBtn](https://github.com/jongpie/NebulaLogger/assets/126723243/d9e958aa-550c-4a26-b1e4-476cdcf29dd0)

**Comment by jongpie** [comment]
Hi @Senay-Ersen - there was a bug in `v4.10.6` for the homepage header component, caused by users not having access to the new Apex controller class `LoggerHomeHeaderController`. If you can upgrade to [`v4.11.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.11.0), that should resolve these issues.

**Comment by Senay-Ersen** [comment]
Hi @jongpie. 
I have upgraded Nebula Logger to v4.11.0 in Dev Org and deployed it to QA Org. Everything is fine in Dev but there is still the same problem in QA. When we click on the `View Environment Details` button, the pop up still comes up empty.  `Nebula Logger: Admin` permission set has access to `LoggerHomeHeaderController ` class but it seems like the `environment ` variable returns empty/null from `getEnvironmentDetails ` method and it causes `showReleaseNotesButton` variable to set to false and the button does not show up on the page.  I am still trying to figure out what I might be missing to deploy, and, in the meantime, I wanted to reach out to you hoping you have any idea on that.

Thanks. 


![image](https://github.com/jongpie/NebulaLogger/assets/126723243/54f00d0c-e083-4a95-8893-f516a087530d)

**Comment by jongpie** [comment]
Hey @Senay-Ersen that's very strange - the controller method is supposed to always return an non-empty/non-null object, so it's possible that there's an exception occurring when the LWC calls the controller method. Could you try calling the controller method from anonymous apex to see if that works for you? You can run something like this snippet to call the controller method:

```java
System.debug('environment details result: ' + JSON.serializePretty(LoggerHomeHeaderController.getEnvironmentDetails()));
```

**Comment by Senay-Ersen** [comment]
Hi @jongpie. I executed the code snippet you have written, and it gives me `'System.CalloutException: Unauthorized endpoint, please check Setup->Security->Remote site settings.'` exception. It made me realize that Remote Site Setting metadata component was not deployed to QA. Once it is deployed, the problem will be resolved. Thanks a lot once more!

**Comment by jongpie** [comment]
Hi @Senay-Ersen, thanks for testing that out! I think this is a bug, so I'll include in a small bugfix in the next release - that callout integration is optional, and in some orgs, they prefer to have the remote site setting deactivated, so I think the code should handle situations where the callout fails. I'm hoping to finish the next release this week.

**Comment by jongpie** [comment]
@Senay-Ersen this should now be fixed in the latest release, [`v4.11.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.11.2)
